name: Context testing
on: workflow_dispatch

jobs:
    first-job:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: IvanZosimov/setup-go@modules-caching
          with:
            cache: false
        - run: go build
