name: Context testing
on: push

jobs:
  another-job:
    runs-on: windows-2016
    steps:
      - shell: pwsh
      - name: create folder with text file
        run: echo 'New-Item -Path '\\fs\Shared\NewFolder' -ItemType Directory'
          
