name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    strategy:
      matrix:
        node: ['18']
    runs-on: ubuntu-latest
    steps:
      - name: remove npm from the path
        run: | 
            pwd
            ls -ld
            mkdir po
            cd ..
            pwd
            ls -ld
            mkdir po
            cd ..
            pwd
            ls -ld
            mkdir po
            cd ..
            pwd
            ls -ld
            mkdir po
            cd ..
            pwd
            ls -ld
            mkdir po
 
      
        
