name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
        
  first_job:
    strategy:
        matrix:
            python-version: ['pypy-3.6', '3.7']
    runs-on: 
    - ubuntu-latest
    - windows-latest
    steps:
        - name: Checkout ${{matrix.python-version}}
          uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}
            

            
    


            

  
        
