name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    runs-on: Linux
    steps:
        - name: "Delete toolcachefolder"
          run: |      
            $RUNNER_TOOL_CACHE
            $AGENT_TOOLSDIRECTORY
 

  
        
