
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
    strategy:
        matrix:
            version: ["3.10"]
            os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ubuntu-latest
    steps:
    - uses: IvanZosimov/setup-python@opt-toolcache
      with: 
         python-version: ${{matrix.version}}


    

       
            

  
        
