name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
    first-job:
      strategy:
        matrix:
          caching: ["true", "false"]
          goSum: ["./go.sum", "./path/go.sum"]
          goMod: ["./go.mod", "./.go-version", ""]
          os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-22.04, ubuntu-18.04, macos-12, macos-10.15, windows-2019, windows-2016 ]
      runs-on: ${{matrix.os}}
      steps:
        - uses: actions/checkout@v3
        - uses: IvanZosimov/setup-go@modules-caching
          with:
            cache: ${{matrix.caching}}
            go-version-file: ${{matrix.goMod}}
            cache-dependency-path: ${{matrix.goSum}}
        - run: go build
