name: Context testing
on: push

jobs:
  another-job:
    runs-on: windows-2016
    steps:
      - name: create folder with text file
        run: echo 'New-Item -Path '\\NewFolder\newfile.txt' -ItemType File'
        shell: pwsh
        
      - name: Fill file with Hello World
        run: echo '$text = 'Hello World dsasdfsxc\asdfasd!' | Out-File $text -FilePath \\NewFolder\newfile.txt -Force'
        shell: pwsh
        
      - name: Open created txt file
        run: echo 'Get-Content \\NewFolder\newfile.txt'
        shell: pwsh
        
