name: Context testing
on: push

jobs:
  setup-go-job:
    runs-on: windows-2016
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
          stable: 'true'
  another-job:
    runs-on: windows-2016
    steps:
      run echo ${{ github }}
          
          
