name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    strategy:
      matrix:
        node: ['18']
    runs-on: macos-latest
    steps:
        
        - uses: IvanZosimov/SomeRepo@main
          with:
             node-version: ${{matrix.node}}
      

  
        
