name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.0.0


