name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Permission reading
        run: |
          export CACHEPATH=$(npm config get cache)
          echo $CACHEPATH
          ls -ld $CACHEPATH
        shell: bash  



