name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3.1.0
          with:
            go-version-file: ./go.mod1
        - run: go build
