name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
  build:
    runs-on: self
    steps:
    - uses: actions/checkout@v3
    - uses: IvanZosimov/setup-python@pythonversionfile
      with:
        python-version: "3.8"
            
    


            

  
        
