name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: jojo43/setup-go@go-version-from-file
          with:
            go-version-file: ./path/.go-version
        - run: go build
