name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
    strategy:
        matrix:
            version: ["3.10"]
    runs-on: self
    steps:
    - uses: actions/setup-python@v3
      id: cp310
      with: 
        python-version: ${{matrix.version}}
    - run: |
          ldd "${RUNNER_TOOL_CACHE}/Python/3.10.5/x64/bin/python"
          file "${RUNNER_TOOL_CACHE}/Python/3.10.5/x64/bin/python"
          readelf -d "${RUNNER_TOOL_CACHE}/Python/3.10.5/x64/bin/python"

            

  
        
