name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    strategy:
      matrix:
        node: ['18']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/checkout@v3
        - uses: IvanZosimov/setup-node@CacheVersionUpdate
          with:
             node-version: ${{matrix.node}}
             cache: 'npm'
      

  
        
