name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    runs-on: Linux
    steps:
        - name: "Delete toolcachefolder"
          run: |      
            echo $RUNNER_TOOL_CACHE
        
 

  
        
