name: Context testing
on: push

jobs:
    first-job:
      runs-on: windows-2016
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: 'npm'
        - run: npm install
        - run: npm start
    reusing-cache-job:
        runs-on: windows-2016
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: 'npm'
        - run: npm install
        - run: npm start
