name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    strategy:
      matrix:
        node: ['18']
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-node@v3
        with:
          cache: "npm"
