name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
  build:
    runs-on: self
    steps:
    - uses: actions/checkout@v3
    - run: echo $RUNNER_TOOL_CACHE
    - run: echo $AGENT_TOOLSDIRECTORY
    - uses: actions/setup-python@v4.0.0
      id: cp310
      with:
        python-version: "3.8"
    - run: python --version
            
    


            

  
        
