name: Context testing
on: push

jobs:
  another-job:
    runs-on: windows-2016
    steps:
      - uses: actions/checkout@v2
    
      - name: Get my file from cache
        uses: actions/cache@v2
        with:
          path: ./TestFolder
          key: mySingleKey
          
      - name: Use cached file
        run: |
          New-Item -Path '.\TestFolder\textfile.txt' -ItemType File
          Get-Content .\TestFolder\textfile.txt
          
        shell: pwsh
              
