name: Context testing
on: push

jobs:
    first-job:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: 'npm'
        - run: npm install
        - run: npm run
    reusing-cache-job:
        needs: first-job
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '14'
            cache: 'npm'
        - run: npm install
        - run: npm run
