
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/setup-dotnet@v2
        with: 
            dotnet-version: '6.0.302'
      - uses: actions/checkout@v3
      - run: |
            cd ConsoleApp3
            dotnet --info
            dotnet run
        
      

