name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
    first-job:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v2
        - uses: IvanZosimov/setup-go@modules-caching
        - run: go build
