name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    strategy:
      matrix:
        node: ['18']
    runs-on: self-hosted
    steps:
      - name: remove npm from the path
        run: | 
            $env:PATH
