
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
    strategy:
        matrix:
            version: ["3.10"]
    runs-on: ubuntu-latest
    env:
        AGENT_TOOLSDIRECTORY1: "/Users/runner/hostedtoolcache/new"
    steps:

    - uses: actions/setup-python@v2
      with: 
         python-version: "3.x"
    - run: |
          echo "$RUNNER_TOOL_CACHE"
          echo "$AGENT_TOOLSDIRECTORY"

    

       
            

  
        
