name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    runs-on: self-hosted
    steps:
        - name: "Delete toolcachefolder"
          run: |      
            echo $RUNNER_TOOL_CACHE
            echo $AGENT_TOOLSDIRECTORY
 

  
        
