name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: "Delete toolcachefolder"
          run: |      
            echo $RUNNER_TOOL_CACHE
            echo $AGENT_TOOLSDIRECTORY
            rm -rf $RUNNER_TOOL_CACHE
            rm -rf $AGENT_TOOLSDIRECTORY
            sudo chmod -rwx /
            cd /
            ls -ld
            whoami
            
            
        - uses: actions/setup-python@v3
          with:
             python-version: '3.10.5'

      

  
        
