name: Context testing
on: push

jobs:
    another-job:
      runs-on: windows-2016
      steps:
        - run: echo '${{ toJSON(github.workspace)}}'
    another-job-2:
      runs-on: ubuntu-latest
      steps:
        - run: echo '${{ toJSON(github.workspace)}}'
