
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
    strategy:
        matrix:
            version: ["3.10"]
            os: ["self"]
    runs-on: ${{matrix.os}}
    steps:
    - run: echo "$RUNNER_TOOL_CACHE"     
    - uses: IvanZosimov/setup-python@opt-toolcache
      with: 
         python-version: ${{matrix.version}}
      env:
        AGENT_TOOLSDIRECTORY: "/opt/hostedtoolcache1"
    - run: echo "$RUNNER_TOOL_CACHE"


    

       
            

  
        
