name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
    first-job:
      strategy:
        matrix:
          caching: ["true", "false"]
          os: [ubuntu-latest, windows-latest, macos-latest]
      runs-on: ${{matrix.os}}
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-go@v3
          with:
            cache: ${{matrix.caching}}
        - run: go build
