name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    strategy:
      matrix:
        node: ['18']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}

      - name: Change cache location
        run: |
          export usualFolder=$(npm config get cache)
          export newFolder="$usualFolder/newfolder"
          echo $newFolder
          npm config set cache $newFolder --global
          npm config get cache
        shell: bash  

      - name: Setup go
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'

