
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
    strategy:
        matrix:
            version: ["3.10"]
    runs-on: macos
    env:
        AGENT_TOOLSDIRECTORY1: "/Users/runner/hostedtoolcache/new"
    steps:

    - uses: IvanZosimov/setup-python@main
      with: 
         python-version: "3.10"
    - run: |
          echo "$RUNNER_TOOL_CACHE"
          echo "$AGENT_TOOLSDIRECTORY"
          otool -L "${RUNNER_TOOL_CACHE}/Python/3.10.5/x64/bin/python"

    

       
            

  
        
