name: Context testing
on: push

jobs:
  setup-go-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '14'
          stable: 'true'
          
