
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
    strategy:
        matrix:
            version: ["3.10.5"]
            os: ["macos-latest"]
    runs-on: ${{matrix.os}}
    steps:
 
    - uses: actions/setup-dotnetn@v2
      with: 
         dotnet-version: 6.0.0
   
