
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
    strategy:
        matrix:
            version: ["3.10"]
    runs-on: macos
    env:
        AGENT_TOOLSDIRECTORY: "/Users/github/Desktop/SH-runner/_work/_tool"
    steps:
    - run: |
        echo "$RUNNER_TOOL_CACHE"
    - uses: IvanZosimov/setup-python@patch
      with: 
         python-version: "3.8"
    - run: |
          echo "$RUNNER_TOOL_CACHE"
          echo "$AGENT_TOOLSDIRECTORY"
          otool -L "${RUNNER_TOOL_CACHE}/Python/3.10.5/x64/bin/python"

    

       
            

  
        
