
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
    strategy:
        matrix:
            version: ["3.10"]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-python@v4
      with: 
         python-version: "3.10-dev"


    

       
            

  
        
