name: Context testing
on: push

jobs:
    another-job:
      runs-on: windows-2016
      steps:
        - uses: IvanZosimov/setup-go@IvansVersion
          with:
            go-version: '1.8.5'
            check-latest: true
