name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: IvanZosimov/setup-node@cache-doesnt-throw
        with:
          node-version: '16'
          cache: 'npm'


