name: Context testing
on: 
    workflow_dispatch:
    push:

jobs:
  first_job:
    strategy:
      matrix:
        os: ['8','10', '12', '14', '16', '18']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Setup go
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.os}}

      - name: Permission reading
        run: |
          npm config get cache
        shell: bash  



