name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
  build:
    runs-on: self
    steps:
    - uses: actions/setup-python@v3
      id: cp310
      with: 
        python-version: '3.6'
    - run: ldd ${{steps.cp310.outputs.python-path}}
            
    


            

  
        
