name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    runs-on: self-hosted
    steps:
        - name: "Delete toolcachefolder"
          run: |      
            $Env:RUNNER_TOOL_CACHE
            $Env:AGENT_TOOLSDIRECTORY
 

  
        
