name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    strategy:
      matrix:
        node: ['18']
    runs-on: macos-latest
    steps:
        
        - uses: actions/setup-java@v3
          with:
             java-version: '17.0.1234'
             distribution: 'zulu'
      

  
        
