name: Context testing
on: push

jobs:
    another-job:
      runs-on: windows-2016
      steps:
        - uses: IvanZosimov/setup-go@v-smurtazin/check-latest-akv-platform
          with:
            go-version: '1.8.6'
            check-latest: true
