name: Context testing
on: push

jobs:
    another-job:
      runs-on: windows-2016
      steps:
        - run: echo '$GITHUB_WORKSPACE'
    another-job-2:
      runs-on: windows-2016
      steps:
        - run: echo '$GITHUB_WORKSPACE'
