name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
        
  first_job:
    strategy:
        matrix:
            python-version: ['3.9']
            os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    runs-on: ${{matrix.os}}
   
    steps:
        - uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}
            
        - run: echo $DISPLAY
          shell: bash
            
    


            

  
        
