name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
        
  first_job:
    strategy:
        fail-fast: false
        matrix:
            python-version: ['3.8.13']
            os: ['macos-latest']
            
    runs-on: ${{matrix.os}}
   
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: ${{matrix.python-version}}

        - run: echo $DISPLAY
        - run: python ./scripts/tcltk.py
          shell: bash

            
    


            

  
        
