
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    environment: build
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ macos-12 ]

    steps:
     
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: "x64"
          cache: 'pip'
      - run: |
          pip install -r requirements.txt
