name: Context testing
on: push

jobs:
    another-job:
      runs-on: windows-2016
      steps:
        - uses: actions/setup-go@v2
          with:
            go-version: '>= 1.15 || <2'
        
        
        
