name: Context testing
on: 
    workflow_dispatch:

jobs:
  first_job:
    strategy:
      matrix:
        node: ['18']
    runs-on: self-hosted
    steps:
      - name: remove npm from the path
        run: | 
            $env:PATH
            $path = [System.Environment]::GetEnvironmentVariable(
                'PATH'
            )
            # Remove unwanted elements
            $path = ($path.Split(';') | Where-Object { $_ -ne 'C:\Users\v-ivzosimov\AppData\Roaming\npm' }) -join ';'
            # Set it
            [System.Environment]::SetEnvironmentVariable(
                'PATH',
                $path
            )
            $env:PATH
