name: Context testing
on: workflow_dispatch

jobs:
    first-job:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: IvanZosimov/setup-go@modules-caching
          with:
            cache: 'true'
        - run: go run .
