name: Context testing
on: 
    workflow_dispatch:
    push:
env:
    NODE_VERSION: '16.0.0'

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION


