
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  test:
    runs-on: macos-latest
 
    steps:
    - run: dotnet --info
    - uses: actions/setup-dotnet@v2
      with: 
         dotnet-version: 3.1
    - run: dotnet --info
   
