
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - run: |
          git config --global user.email "pythonversionbot@bot.com"
          git config --global user.name "PythonVersionBot"
          git clone https://github.com/IvanZosimov/TestRepo2.git
          cd TestRepo2
          sed -i -e 's/3.7/3.8/g' ./.python-version
          git add -A
          git commit -m "Update to 3.8"
          git push origin main
        

