name: 'Test GRAPHQL'
on:
  workflow_dispatch

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: bearer ${{secrets.PAT}}" -X POST -d " \
          { \
          \"query\": \"query { viewer { login }}\" \
          } \
          " https://api.github.com/graphql

