name: 'Test triggering'
on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.issue.number }}
          echo ${{ github.repository }}
          echo ${{ github.event.sender.login }}

