name: 'Test triggering'
on:
  issues:
    types: opened
  pull_request:
    types: opened

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ github.event.issue.number }}
          echo ${{ github.repository }}
          echo ${{ github.event.sender.login }}
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{github.token}}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"Hi, @${{ github.event.sender.login }} thanks for the issue! We will take a loot at it and get back to you with updates."}'

