
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
     - name: checkout-code
       uses: actions/checkout@v3    
     - uses: actions/setup-go@v3
       with:
        go-version: "1.18.x"
