
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        dotnet: ["7.0.100-preview.7.22377.5"]
        os: ['ubuntu-latest','macos-latest', 'windows-latest']
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3

        
      - name: ${{matrix.os}} ${{matrix.quality}}

        uses: IvanZosimov/setup-dotnet@ADRdotnet
                
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - run: |
            dotnet --info



      
        
      

