
name: Context testing
on: 
    workflow_dispatch:
    pull_request: 
        types: [opened]
    issues: 
        types: [opened]
    
jobs:
  create-response:
    runs-on: ubuntu-latest
    steps:
    - name: Get issue information
      id: unique-id
      run: |
        $Name = "@${{github.event.sender.login}}"
        echo "ISSUE_NUMBER=${{github.event.issue.number}}" >> $Env:GITHUB_OUTPUT
        echo "PR_NUMBER=${{github.event.pull_request.number}}" >> $Env:GITHUB_OUTPUT
        echo "NAME=$($Name)" >> $Env:GITHUB_OUTPUT
      shell: pwsh
      
    - name: Response to the newly created Issue
      if: ${{ github.event_name == 'issues' }}
      run: |
        echo ${{ steps.unique-id.outputs.ISSUE_NUMBER }}
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{github.token}}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{github.repository}}/issues/${{ steps.unique-id.outputs.PR_NUMBER }}/comments \
        -d '{"body":"Test Comment"}'
        echo "Comment created"

    - name: Response to the newly created PR
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo ${{ steps.unique-id.outputs.ISSUE_NUMBER }}
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{github.token}}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{github.repository}}/issues/${{ steps.unique-id.outputs.PR_NUMBER }}/comments \
        -d '{"body":"Test Comment"}'
        echo "Comment created"
        echo "PR created"
      shell: pwsh
