
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/runtime-deps:3.0-bionic
      options: --dns 127.0.0.1
    services:
      squid-proxy:
        image: ubuntu/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://squid-proxy:3128
      http_proxy: http://squid-proxy:3128
    steps:
      - name: Install Powershell
        run: |
          apt-get update
          apt-get install -y powershell
          pwsh -v
        

