
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  test-proxy:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/core/runtime-deps:3.0-bionic
      options: --dns 127.0.0.1
    services:
      squid-proxy:
        image: datadog/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://squid-proxy:3128
      http_proxy: http://squid-proxy:3128
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clear tool cache
        run: rm -rf "/usr/share/dotnet"
      - name: Install curl
        run: |
          apt update
          apt -y install curl
      - name: Setup dotnet 3.1.201
        uses: IvanZosimov/setup-dotnet@ADRdotnet
        with:
          dotnet-version: 3.1.201
          source-url: https://api.nuget.org/v3/index.json
        env:
          NUGET_AUTH_TOKEN: NOTATOKEN
      - name: Verify dotnet
        run: |
            dotnet --version
            dotnet --info


      
        
      

