
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
    name: Dotnet sample
    steps:
    - name: Checkout
      uses: actions/checkout@main
          

    - uses: actions/setup-python@v4
      id: cp310
    - run: echo '${{ steps.cp310.outputs.python-version }}'

  
      

