
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: Dotnet sample
    steps:
      - uses: actions/checkout@v3

        
      - name: ${{matrix.os}} ${{matrix.quality}}

        uses: IvanZosimov/setup-dotnet@dotnetOutput
        id: cp310
        with:
          dotnet-version: | 
            2.1.x
            7.0.x
            3.1.x
      - run: |
            echo '${{ steps.cp310.outputs.dotnet-version }}'
    



      
        
      

