
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['windows-latest']
    name: Dotnet sample
    steps:
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: IvanZosimov/setup-dotnet@dotnetOutput
      id: cp310
      with:
        dotnet-version: |
            6.x
    - run: |
        echo '${{ steps.cp310.outputs.dotnet-version }}'
        dotnet --version
  
      

