
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
     - run: |
        Write-Host "##vso[task.logissue type=error;] Unexpected failure occurs while configuring git preferences."
       shell: pwsh
