
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        vs: [ "6.x"]

    steps:
      - uses: actions/setup-dotnet@v2
        with: 
            dotnet-version: ${{matrix.vs}}
            include-prerelease: true
      
        
      

