name: Context testing
on: 
    workflow_dispatch:

jobs:
   board-automation:
    strategy:
        matrix:
            os: [windows-latest]
    runs-on: ${{matrix.os}}
    steps:
        - run: |
            dotnet --info
        # - uses: actions/setup-java@v3
        #   with:
        #       java-version: '17'
        #       distribution: 'adopt'
        #       check-latest: 'false'

