
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    env:
        DOTNET_INSTALL_DIR: '/usr/share/dotnet/zzz'
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: setup-node@v3 node-version-file check
    steps:
    - run: |
        cd '/usr/share/dotnet'
        mkdir 'zzz'
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: IvanZosimov/setup-dotnet@dotnet-install-dir-fix
      with:
          dotnet-version: '7.0'


  

    - run: |
        dotnet --info
        
    
        
  
      

