
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
              
     - uses: actions/setup-dotnet@teo-tsirpanis:patch-1
 
          
  
      

