
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test:
    name: Run test
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: "20-ea"
        distribution: temurin

