
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup dotnet 3.1
        uses: IvanZosimov/setup-dotnet@ADRdotnet
        with:
          dotnet-version: '3.1'
      - name: Verify dotnet
        run: |
            /usr/share/dotnet --version
            /usr/share/dotnet --info


      
        
      

