
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix: 
        dist: ['corretto']
        os: ["ubuntu-latest"]
        version: [11]
    runs-on: ${{matrix.os}}
    
    

    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{matrix.dist}}
          java-version: ${{matrix.version}}
      - run: |
            mv  /opt/hostedtoolcache/Java_Corretto_jdk/11.0.18.10.1 /opt/hostedtoolcache/Java_Corretto_jdk/11.0.18+10.1
            cp -R /opt/hostedtoolcache/Java_Corretto_jdk/11.0.18.10.1/* /opt/hostedtoolcache/Java_Corretto_jdk/11.0.18+11.1
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{matrix.dist}}
          java-version: ${{matrix.version}}
