
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 5.0.x
          
      - name: Print dotnet version without exe (using PATH, ignore error)
        continue-on-error: true
        run: |
          dotnet --version
      - name: Print dotnet version (using PATH, ignore error)
        continue-on-error: true
        run: |
          dotnet.exe --version

      - name: Print dotnet version (using fullpath to executable)
        run: |
          & "C:\Program Files\dotnet\dotnet" --version
        

