
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          version: ["7.0.1xx"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
      - uses: actions/setup-dotnet@main
        with:
            dotnet-version: ${{matrix.version}}
            dotnet-quality: "preview"
        id: dotnet
      - run: |
          echo ${{steps.dotnet.outputs.dotnet-version}}

            
          
        

