
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    env:
        NUGET_PACKAGES: ${{ github.workspace }}/hru/.nuget/packages
    steps:
      - uses: actions/checkout@v3
      - uses: akv-platform/setup-dotnet@add-latest-patch-syntax
        id: stepId
        with:
          dotnet-version: |
            3.1
            6.0.2xx
            7.0
            2.0
      - run: |
            echo "${{steps.stepId.outputs.dotnet-version}}"
            
          
        

