
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    #env:
        #NUGET_PACKAGES: ${{ github.workspace }}/hru/.nuget/packages
    steps:
      - uses: actions/checkout@v3
      - uses: nogic1008/setup-dotnet@feat/nuget-cache
        with:
           cache: true
           dotnet-version: "2.0"
      - run: |
            dotnet restore test.csproj

            
          
        

