
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ['5.0.x' ]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: IvanZosimov/setup-dotnet@ADRdotnet
        with:
          dotnet-version: ${{ matrix.dotnet }}
          dotnet-quality: "preview"
      - run: |
            dotnet --version
            dotnet --info      


      
        
      

