
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
        dotnet: [ '2.1.x' ]
    steps:
     - name: checkout-code
       uses: actions/checkout@v3    
     - uses: IvanZosimov/setup-dotnet@test
       id: installationStep
       with:
        dotnet-version: ${{ matrix.dotnet }}
