name: Context testing
on: 
    workflow_dispatch:

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/setup-go@main
          with:
            go-version: "1.21"
            cache: false

