name: Context testing
on: 
#     issues:
#       types: [opened]
    workflow_dispatch:
#       inputs:
#         logIntoSlack:
#           description: 'Send message to the Slack channel?'
#           required: false
#           default: true
#           type: boolean

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 17
        - uses: gradle/gradle-build-action@v2
          with:
            gradle-version: "6.8.3"
        - run: gradle --version
