
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    name: setup-node@v3 node-version-file check
    steps:
    - name: Create dir
      run: |
        cd $HOME
        mkdir "zzz"
        
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: actions/setup-dotnet@v3
      with:
          dotnet-version: '7.0'
      env:
        DOTNET_INSTALL_DIT: '${{$HOME}}/zzz'


  

    - run: |
        dotnet --info
        
    
        
  
      

