name: Test
on: 
    workflow_dispatch:

jobs:
  maven-save:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - run: node -v
      # - uses: actions/checkout@v4
      - name: Setup java
        uses: IvanZosimov/setup-java@v-dmshib/add-arm64-windows-microsoft
        with:
          java-version: "17.0.7"
          distribution: "microsoft"
          architecture: "x64"
