
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      options: --dns 127.0.0.1
    services:
      squid-proxy:
        image: ubuntu/squid:latest
        ports:
          - 3128:3128
    env:
      https_proxy: http://squid-proxy:3128
      http_proxy: http://squid-proxy:3128
    steps:
      - name: Install Powershell
        run: |
          apt update
          apt -y install curl
        

