name: Context testing
on: 
    issues:
      types: [opened]
    schedule:
      - cron: '* * * * 1-5'
    workflow_dispatch:
      inputs:
        logIntoSlack:
          description: 'Send message to the Slack channel?'
          required: false
          default: true
          type: boolean

jobs:
   board-automation:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
        node-version: 'lts/*'
     - run: |
        echo ${{ inputs.logIntoSlack == '' || inputs.logIntoSlack  }}
       env:
        LOG_INTO_SLACK: ${{ inputs.logIntoSlack }}
