
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['self-hosted']
    name: setup-node@v3 node-version-file check
    steps:
       
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: actions/setup-dotnet@v3
      id: cp310
      with:
          dotnet-version: |
            7.0
      env:
        DOTNET_INSTALL_DIR: '~/AppData/Local/Microsoft/dotnet'
    - run: |
        echo '${{steps.cp310.outputs.dotnet-version}}'
        dotnet --info
        
    
        
  
      

