
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          version: ["2.1.202"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    #env:
        #NUGET_PACKAGES: ${{ github.workspace }}/hru/.nuget/packages
    steps:
      - uses: actions/checkout@main
      - run: |
         dotnet --version
         dotnet nuget locals all --list --force-english-output
         cd ./e2e-test-csproj
         dotnet nuget locals all --list --force-english-output

            
          
        

