
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v3
    - run: |
        wget https://download.java.net/java/GA/jdk19.0.1/afdd2e245b014143b62ccb916125e3ce/10/GPL/openjdk-19.0.1_macos-x64_bin.tar.gz 
    - uses: actions/setup-java@v3
      with:
        java-version: 19.0.1
        distribution: jdkfile
        jdkFile: openjdk-19.0.1_macos-x64_bin.tar.gz
        
    - run: |
        ls -lf /opt/hostedtoolcache/Java_jdkfile_jdk/19.0.1/contents
        
