
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        vs: [ "7.0.x"]

    steps:
      - uses: actions/checkout@v3
      - uses: IvanZosimov/setup-dotnet@ADRdotnet
        with: 
            dotnet-version: |
               7.0
               6.0
               5.0
               
            dotnet-quality: "some"
      - run: dotnet --info

      
        
      

