name: Context testing
on: 
#     issues:
#       types: [opened]
    workflow_dispatch:
#       inputs:
#         logIntoSlack:
#           description: 'Send message to the Slack channel?'
#           required: false
#           default: true
#           type: boolean

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '11.0.9+11'

