name: Context testing
on: 
    workflow_dispatch:

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]
            version: ["8.0.2-preview.3"]
    runs-on: ${{matrix.os}}
    steps:
        - uses: Accelerator1996/setup-java@main
          with:
            java-version: ${{matrix.version}}
            distribution: "dragonwell"
        - run: java -version

