
name: Context testing
on: 
    workflow_dispatch:
    pull_request: 
        types: [opened]
    issues: 
        types: [opened]
    
jobs:       
  build:
    runs-on: ubuntu-latest
    steps:
      - run: | 
            curl -H "Authorization: bearer ${{github.token}}" -X POST -d " \
            { \
             \"query\": \"query { viewer { login }}\" \
             } \
            " https://api.github.com/graphql
