
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        vs: [ "3.8", "3.8-dev"]

    steps:
      - uses: actions/setup-python@v4
        with: 
            python-version: ${{matrix.vs}}
      
        
      

