name: Context testing
on: 
    workflow_dispatch:

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest]
            version: ["21"]
            distro: ["temurin", "adopt", "liberica", "adopt-openj9", "liberica", "microsoft", "corretto", "semeru"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
        - uses: actions/setup-java@v3
          
          with:
            java-version: ${{matrix.version}}
            distribution: ${{matrix.distro}}

