
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: Dotnet sample
    steps:
      - uses: actions/checkout@v3

        
      - name: ${{matrix.os}} ${{matrix.quality}}

        uses: IvanZosimov/setup-dotnet@ADRdotnet

        with:
          dotnet-version: "6.x"
          dotnet-quality: "daily"
      - run: |
            dotnet --info
