name: Test
on: 
    workflow_dispatch:

jobs:
   test:
    strategy:
        matrix:
            os: [ubuntu-latest]
            version: ["21"]
            distro: ["temurin", "zulu", "adopt", "adopt-openj9", "liberica", "microsoft", "corretto", "semeru", "oracle", "dragonwell"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
        - uses: actions/checkout@v3
        - uses: akv-platform/setup-java@action_cache_update
          with:
            java-version: ${{matrix.version}}
            distribution: ${{matrix.distro}}

