
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    name: Dotnet sample
    steps:
    - run: |
        cd '/usr/share/dotnet'
        mkdir 'zzz'
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: IvanZosimov/setup-dotnet@dotnet-install-dir-fix
      id: cp310
      with:
          dotnet-version: |
            3.1
            2.1
            7.0
    - run: |
        echo '${{ steps.cp310.outputs.dotnet-version }}'
        dotnet --info
        
    
        
  
      

