
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        vs: [ "7.0.x"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with: 
            dotnet-version: "bla"
                         
      - run: dotnet --info

      
        
      

