
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['macos-latest']
    name: Dotnet sample
    steps:
          

      - run: |
            ls "/usr/local/bin/dotnet"
