
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['windows-latest']
    name: setup-node@v3 node-version-file check
    steps:
              
     - uses: IvanZosimov/setup-dotnet@Test
       with:
          dotnet-version: |
              3.1.202
       env:
         DOTNET_INSTALL_DIR: "%LocalAppData%/Microsoft/dotnet"
     - run: dotnet --info
        
    
        
  
      

