name: Test
on: 
    workflow_dispatch:

jobs:
  maven-save:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run setup-java with the cache for maven
        uses: actions/setup-java@v3
        id: setup-java
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: maven
      - name: Create files to cache
        run: |
          mvn verify -f ./pom.xml
          if [ ! -d ~/.m2/repository ]; then
            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
            exit 1
          fi
  maven-restore:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    needs: maven-save
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run setup-java with the cache for maven
        uses: actions/setup-java@v3
        id: setup-java
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: maven
      - name: Confirm that ~/.m2/repository directory has been made
        run: |
          if [ ! -d ~/.m2/repository ]; then
            echo "::error::The ~/.m2/repository directory does not exist unexpectedly"
            exit 1
          fi
          ls ~/.m2/repository
