
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['windows-latest']
    name: setup-node@v3 node-version-file check
    steps:
              
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10.x"

        
    
        
  
      

