
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['macos-latest']
    name: Dotnet sample
    steps:
          

      - run: |
            find /Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib -name "Xamarin.Android.CSharp.targets"
