
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          version: ["6.0"]
    runs-on: ${{matrix.os}}
    
    steps:
      - uses: actions/checkout@v3
      - uses: nogic1008/setup-dotnet@feat/nuget-cache
        with:
          dotnet-version: ${{matrix.version}}
          cache: true
          cache-dependency-path: "**/packages.lock.json"
      - run: |
            dotnet restore test.csproj
          
        

