name: Context testing
on: 
#     issues:
#       types: [opened]
    workflow_dispatch:
#       inputs:
#         logIntoSlack:
#           description: 'Send message to the Slack channel?'
#           required: false
#           default: true
#           type: boolean

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
        - run: |
            echo $RUNNER_ENVIRONMENT
            echo $AGENT_ISSELFHOSTED
          if: ${{ matrix.os != "windows-latest" }}
        - run: |
            echo $Env:RUNNER_ENVIRONMENT
            echo $Env:AGENT_ISSELFHOSTED
          if: ${{ matrix.os == "windows-latest" }}
