name: Context testing
on: 
    workflow_dispatch:

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest]
            version: ["11"]
    runs-on: ${{matrix.os}}
    steps:
        - uses: Accelerator1996/setup-java@main
          with:
            java-version: ${{matrix.version}}
            distribution: "dragonwell"
            architecture: "bla"
        - run: java -version

