
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: setup-dotnet@v3
    steps:
    - name: Checkout
      uses: actions/checkout@v3
          
    - uses: actions/setup-dotnet@v3
      id: cp310
      with:
          dotnet-version: '3.x'
    - run: |
        echo '${{ steps.cp310.outputs.dotnet-version }}'

        
    
        
  
      

