
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest', 'ubuntu-latest']

    steps:
    - uses: actions/checkout@v3
    - run: |
        wget https://download.oracle.com/java/19/latest/jdk-19_linux-x64_bin.tar.gz 
    - uses: actions/setup-java@v3
      with:
        java-version: 19.0.2
        distribution: jdkfile
        jdkFile: jdk-19_linux-x64_bin.tar.gz
        
    - run: |
        echo $JAVA_HOME
        mvn -version
        
