
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ['windows-latest']
    steps:
        - name: Checkout tools repo
          uses: actions/checkout@v3
          with:
            repository: akv-platform/setup-java
            ref: update-configs
        - run: |
            npm run ci
            npm run build
            git diff --ignore-space-at-eol --compact-summary ./dist
