name: Context testing
on: 
#     issues:
#       types: [opened]
    workflow_dispatch:
#       inputs:
#         logIntoSlack:
#           description: 'Send message to the Slack channel?'
#           required: false
#           default: true
#           type: boolean

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
        - uses: IvanZosimov/setup-go@performance
          with:
            go-version: "1.20.6"
