
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['windows-latest']
    name: Dotnet sample
    steps:
    - run: |
        cd 'C:\Program Files\dotnet\sdk'
        mkdir "zzz"
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 7.0
      env:
        DOTNET_INSTALL_DIR: 'C:\Program Files\dotnet\sdk\zzz'
  

    - run: |

        dotnet --info
        
  
      

