
name: Context testing
on: 
    workflow_dispatch:
    pull_request: 
        types: [opened]
    issues: 
        types: [opened]
    
jobs:
  create-response:
    runs-on: ubuntu-latest
    steps:
    - name: Create greeting
      run: |
        $Name = "@${{github.event.sender.login}}"
        echo $Name
      shell: pwsh
      
    - run: |
        echo ${{ toJSON(github.event) }}
    - name: Response to the newly created Issue
      if: ${{ github.event_name == 'issues' }}
      run: |
        echo "Issue created"
      shell: pwsh

    - name: Response to the newly created PR
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo "PR created"
      shell: pwsh
