
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    name: setup-node@v3 node-version-file check
    steps:
       
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: IvanZosimov/setup-dotnet@dotnet-install-dir-fix
      with:
          dotnet-version: '7.0'
      env:
        DOTNET_INSTALL_DIR: './zzz'

    - run: |
        dotnet --info
        
    
        
  
      

