
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix: 
        dist: ['temurin', 'zulu', 'microsoft', 'adopt']
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        version: [8, 11, 17]
    runs-on: ${{matrix.os}}


    steps:
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{matrix.dist}}
          java-version: ${{matrix.version}}
