name: Test
on: 
    workflow_dispatch:

jobs:
   test:
    strategy:
        matrix:
            os: [ubuntu-latest]
            version: ["21"]
            distro: ["temurin"]
    runs-on: ${{matrix.os}}
    # continue-on-error: true
    env:
      SEGMENT_DOWNLOAD_TIMEOUT_MINS: '5'
    steps:
        - uses: akv-platform/setup-java@action_cache_update
          with:
            java-version: ${{matrix.version}}
            distribution: ${{matrix.distro}}
            cache: "maven"
        - run: |
            echo $JAVA_HOME
            which java
            java --version

