
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          version: ["6.0"]
    runs-on: ${{matrix.os}}
    env:
        NUGET_PACKAGES: ${{ github.workspace }}/hru/.nuget/packages
    steps:
      - uses: actions/checkout@v3
      - uses: nogic1008/setup-dotnet@feat/nuget-cache
        id: stepId
        with:
          dotnet-version: |
            5.0
          cache: true
      - run: |
            dotnet restore
            echo "${{steps.stepId.outputs.dotnet-version}}"
            
          
        

