
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['self-hosted']
    name: setup-node@v3 node-version-file check
    steps:
       
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: IvanZosimov/setup-dotnet@dotnet-install-dir-fix
      id: cp310
      with:
          dotnet-version: |
            7.0
            6.0
            3.1
            3.0

    - run: |
        echo '${{steps.cp310.outputs.dotnet-version}}'
        dotnet --info
        
    
        
  
      

