name: Test
on: 
    workflow_dispatch:

jobs:
  maven-save:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - run: node -v
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.x.x
          source-url: https://nuget.pkg.github.com/xxxx/index.json
      - run: echo $NUGET_AUTH_TOKEN
