
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: setup-dotnet@v3
    steps:
    - name: Checkout
      uses: actions/checkout@v3
          
    - uses: actions/setup-node@v3
      with:
          node-version-file: 'package.json'
    - name: Show the installed node.js version
      run: |
        node -v

        
    
        
  
      

