
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          version: ["1.1.14", "2.1.202", "2.2.100", "3.0.103", "3.1.426"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    #env:
        #NUGET_PACKAGES: ${{ github.workspace }}/hru/.nuget/packages
    steps:
      - uses: actions/checkout@main
      - run: |
         ./clearDotnetToolcache.ps1 ${{ runner.os }}
        shell: pwsh
      - uses: actions/setup-dotnet@main
        with:
            dotnet-version: ${{matrix.version}}
      - run: |
         dotnet new globaljson --sdk-version ${{matrix.version}}
         dotnet --version
         dotnet nuget locals all --list --force-english-output

            
          
        

