
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: Dotnet sample
    steps:

    - name: Checkout
      uses: actions/checkout@main
          
    - uses: actions/setup-dotnet@v2
      with:
          dotnet-version: '7.0'
          include-prerelease: true

  

    - run: |

        dotnet --info
        
  
      

