
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
    
  build:
  
    runs-on:  macos-latest


    steps:
      - uses: actions/checkout@v3
      - uses: IvanZosimov/setup-dotnet@ADRdotnet
        with: 
            dotnet-version: '2.1'
            dotnet-quality: "preview"
      - run: |
            dotnet --info
        


      
        
      

