
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          version: ["6.0.2xx", "3.0.1xx", "3.1", "6.0.x"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    env:
        NUGET_PACKAGES: ${{ github.workspace }}/hru/.nuget/packages
    steps:
      - uses: actions/checkout@v3
      - uses: akv-platform/setup-dotnet@add-latest-patch-syntax
        id: stepId
        with:
          dotnet-version: ${{matrix.version}}
          dotnet-quality: "preview"

      - run: |

            echo "${{steps.stepId.outputs.dotnet-version}}"
            
          
        

