
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-hosted']
    name: setup-node@v3 node-version-file check
    steps:
              
     - uses: actions/setup-dotnet@main
       with:
          dotnet-version: |
              6.0.x
       env:
        DOTNET_INSTALL_DIR: "../.dotnet"

        
    
        
  
      

