name: Test
on: 
    workflow_dispatch:

jobs:
   test:
    strategy:
        matrix:
            os: [ubuntu-latest]
            version: ["21"]
            distro: ["oracle"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
        - uses: actions/setup-java@v3
          
          with:
            java-version: ${{matrix.version}}
            distribution: ${{matrix.distro}}
        - run: |
            echo $JAVA_HOME
            which java
            java --version

