
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        dotnet: [""]
        os: ['ubuntu-latest']
        quality: ["preview"]
    name: Dotnet ${{ matrix.dotnet }} sample
    steps:
      - uses: actions/checkout@v3

        
      - name: ${{matrix.os}} ${{matrix.quality}}

        uses: IvanZosimov/setup-dotnet@ADRdotnet
        
        
        with:
          dotnet-version: ${{ matrix.dotnet }}
          dotnet-quality: ${{matrix.quality}}
      - run: |
            dotnet --version
            dotnet --info



      
        
      

