
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: Dotnet sample
    steps:
    - name: Checkout
      uses: actions/checkout@main
          

    - uses: IvanZosimov/setup-dotnet@ADRdotnet
      id: cp310
      with:
        dotnet-version: |
            6.0.401
            6.x
            7.x
            7.*
            *
            x
            6.0.x
            3.x
            7.0.100-rc.1.22431.12
        dotnet-quality: "daily"
    - run: echo '${{ steps.cp310.outputs.dotnet-version }}'

  
      

