
name: Context testing
on: 
    workflow_dispatch:
    pull_request: 
        types: [opened]
    issues: 
        types: [opened]
    
jobs:
  automatic-reply:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo ${{ github.event.pull_request}}
      
#   call-reusable-workflow:
#     name: automatic reply
#     uses: akv-platform/reusable-workflows/.github/workflows/automatic-reply.yml@add-automatic-response
