name: Context testing
on: 
#     issues:
#       types: [opened]
    workflow_dispatch:
#       inputs:
#         logIntoSlack:
#           description: 'Send message to the Slack channel?'
#           required: false
#           default: true
#           type: boolean

jobs:
   board-automation:
    strategy:
        matrix:
            os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/checkout@v3
        - uses: Endi327/setup-java@include-versions.properties-in-cache-key
          with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '17'
            cache: 'gradle'
