
name: Context testing
on: 
    workflow_dispatch:
    pull_request: 
        types: [opened]
    issues: 
        types: [opened]
    
jobs:       
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/graphql-action@v2.x
        id: get_info
        with:
          query: |
            query {
              organization(login: "actions") {
                projectV2(number: 19) {
                  items(first: 1, after: "") {
                    edges {
                      cursor
                      node {
                        fieldValueByName(name: "Status") {
                          ... on ProjectV2ItemFieldSingleSelectValue {
                            optionId
                          }
                        }
                        content {
                          ... on PullRequest {
                            url
                          }
                          ... on Issue {
                            url
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_info.outputs.data }}'"
