
name: Context testing
on: 
    workflow_dispatch:
    pull_request: 
        types: [opened]
    issues: 
        types: [opened]
    
jobs:
  call-reusable-workflow:
    name: automatic reply
    uses: akv-platform/reusable-workflows/.github/workflows/automatic-response.yml@add-automatic-response
