
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['windows-latest']
    steps:
              
     - uses: actions/setup-dotnet@v2
       with:
          dotnet-version: "6.0.x"
          include-prerelease: true
    
        
  
      

