
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['windows-latest']
    steps:
              
     - uses: actions/setup-dotnet@v3
       env:
        DOTNET_INSTALL_DIR: "./newFolder"
       with:
        dotnet-version: "6.0.x"
     
     - run: dotnet nuget --version
     - run: $env:PATH
     
 
          
  
      

