name: Test
on: 
    workflow_dispatch:

jobs:
   test:
    strategy:
        matrix:
            os: [ubuntu-latest]
            version: ["17"]
            distro: ["temurin"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
        - uses: actions/setup-java@v3
          
          with:
            java-version: ${{matrix.version}}
            distribution: ${{matrix.distro}}
            java-package: 'jre'
        - run: echo $JAVA_HOME

