
name: Context testing
on: 
    workflow_dispatch:
    pull_request: 
        types: [opened]
    issues: 
        types: [opened]
    
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
     - run: |
         echo {{toJSON(${{github.event}})
