
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    steps:
     - uses: actions/labeler@max
       with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
