
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test:
    name: Run test
    strategy:
        matrix:
            distrib: ["temurin", "zulu", "adopt", "adopt-openj9", "liberica", "microsoft", "corretto", "semeru", "oracle"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: ${{matrix.distrib}}
    - uses: actions/setup-java@v3
      with:
        java-version: "17"
        distribution: ${{matrix.distrib}}

