
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
        dotnet: [ '2.1.x', '3.1.x', '5.0.x' ]
    steps:
     - name: checkout-code
       uses: actions/checkout@v3    
     - uses: actions/setup-dotnet@v3
       id: cp310
       with:
        dotnet-version: ${{ matrix.dotnet }}
     - run: | 
        echo '{"sdk":{"version": "${{ steps.cp310.outputs.dotnet-version }}"}}' > ./global.json
        cat ./global.json
        dotnet --version
