
name: Context testing
on: 
    workflow_dispatch:
    #push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          version: ["7.0"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - run: |
            ./clearDotnetToolcache.ps1 ${{runner.os}}
        shell: pwsh
      - uses: nogic1008/setup-dotnet@feat/nuget-cache
        with:
            dotnet-version: ${{matrix.version}}
#             cache: true
        id: dotnet
      - run: |
            dotnet restore ./e2e-test-csproj/test.csproj
      - run: |
          echo ${{steps.dotnet.outputs.dotnet-version}}
          echo ${{steps.dotnet.outputs.cache-hit}}

            
          
        

