
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        vs: [ "7.0.x"]

    steps:
      - uses: actions/checkout@v3
      - uses: IvanZosimov/setup-dotnet@ADRdotnet
        with: 
            dotnet-version: |
                "6.0"
                "6.0.x"
                "6.0.*"
                "6.0.X"
                "5.0.408"
                "7.0.0-preview.7.22375.6"
                         
      - run: dotnet --info

      
        
      

