name: Context testing
on: 
#     issues:
#       types: [opened]
    workflow_dispatch:
#       inputs:
#         logIntoSlack:
#           description: 'Send message to the Slack channel?'
#           required: false
#           default: true
#           type: boolean

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-java@v3
#        with:
#         java-version: '17.0.2+8'
#         distribution: 'temurin'
      - run: gradle --version
