
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test1:
    strategy:
        matrix:
          os: ["ubuntu-latest", "macos-latest", "windows-latest"]
          version: ["2.1.2xx", "3.1.2xx", "5.0.1xx", "6.0.2xx", "7.0.1xx"]
    runs-on: ${{matrix.os}}
    continue-on-error: true
    #env:
        #NUGET_PACKAGES: ${{ github.workspace }}/hru/.nuget/packages
    steps:
      - uses: actions/setup-dotnet@main
        id: dotnet
        with:
            dotnet-version: ${{matrix.version}}
      - run: |
          echo ${{steps.dotnet.outputs.dotnet-version}}

            
          
        

