
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['windows-latest']
    steps:
              
     - uses: actions/setup-dotnet@v3
       with:
          dotnet-version: "6.0.x"
          include-prerelease: true
    
     - name: Install EF Tool
       run: |
          dotnet new tool-manifest
          dotnet tool install dotnet-ef
          cd "C:\Program Files\dotnet\packs\Microsoft.NET.Runtime.WebAssembly.Sdk\6.0.10\Sdk"
          Get-Content WasmApp.targets
          
  
      

