
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
        version: ["6.0.401", "7.x", "5.x", "4.x", "3.x", "2.x" ]
    name: Dotnet sample
    steps:
          
    - name: Test setup-dotnet v3
      uses: IvanZosimov/setup-dotnet@ADRdotnet
      with: 
        dotnet-version: |
            6.0.401
            7.x
            5.x
            4.x
            3.x
            2.x
    - name: Check installed
      run: dotnet --info

  
      

