
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: Dotnet sample
    steps:
    - run: |
        cd '/home/runner/.dotnet/sdk'
        mkdir 'zzz'
    - name: Checkout
      uses: actions/checkout@main
          
    - uses: actions/setup-dotnet@v2
      with:
          dotnet-version: '7.0'
          include-prerelease: true
      env:
        DOTNET_INSTALL_DIR: "/home/runner/.dotnet/sdk/zzz"

  

    - run: |

        dotnet --info
        
  
      

