name: Context testing
on: 
#     issues:
#       types: [opened]
    workflow_dispatch:
#       inputs:
#         logIntoSlack:
#           description: 'Send message to the Slack channel?'
#           required: false
#           default: true
#           type: boolean

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-self-hosted]
            try: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n"]
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/setup-java@v3
          with:
            distribution: 'adopt'
            java-version: '17'

