
name: Context testing
on: 
    workflow_dispatch:
    pull_request: 
        types: [opened]
    issues: 
        types: [opened]
    
jobs:
  create-response:
    runs-on: ubuntu-latest
    steps:
    - name: Get issue information
      id: unique
      run: |
        $Greeting = "Hello, <userName>! How are you?"
        $Name = "@${{github.event.sender.login}}"
        $PrNumber = "${{github.event.pull_request.number}}"
        $IssueNumber = "${{github.event.issue.number}}"
        echo "ISSUE_NUMBER=$($IssueNumber)" >> "$GITHUB_OUTPUT"
        echo "PR_NUMBER=$($PrNumber)" >> "$GITHUB_OUTPUT"
      shell: pwsh
      
    - name: Response to the newly created Issue
      if: ${{ github.event_name == 'issues' }}
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer <YOUR-TOKEN>"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/IvanZosimov/Test2/issues/${{ steps.unique.outputs.ISSUE_NUMBER }}/comments \
        -d '{"body":"Test Comment"}'
        echo "Comment created"
      shell: pwsh

    - name: Response to the newly created PR
      if: ${{ github.event_name == 'pull_request' }}
      run: |
        echo "PR created"
      shell: pwsh
