
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    name: Dotnet sample
    steps:
      - uses: actions/checkout@v3

        
      - name: ${{matrix.os}} ${{matrix.quality}}

        uses: IvanZosimov/setup-dotnet@dotnetOutput 
        id: cp310
        with:
          dotnet-version: | 
            7.0.100-preview.7.22377.5
            3.1.x
            6.0.x
      - run: |
             echo '${{ steps.cp310.outputs.dotnet-version }}'
    



      
        
      

