
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: aleksandrlevochkin/print-info@main
        with:
          owner-name: "actions"
          repository-name: "setup-dotnetXXX"
          from-date: "01/01/2023"
          github-token: ${{github.token}}
        

