
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: akv-platform/setup-dotnet@add-latest-patch-syntax
        with:
          dotnet-version: "3.1.2xx"
        

