name: Context testing
on: 
    workflow_dispatch:

jobs:
   board-automation:
    strategy:
        matrix:
            os: [ubuntu-latest]
            version: ["11", "17.x", "11.0.18+14.9"]
    runs-on: ${{matrix.os}}
    steps:
        - uses: actions/setup-java@v3
          with:
            java-version: ${{matrix.version}}
            distribution: "dragonwell"
        - run: java -version

