
name: Context testing
on: 
    workflow_dispatch:
    push:
    

jobs:
    
  build:
  
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        vs: [ "7.0.x"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
            cache: "pip"
      - run: pip install -r requirements.txt
      
        
      

