
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  test:
    name: Run test
    strategy:
        matrix:
            distrib: ["corretto", "zulu"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: akv-platform/setup-dotnet@add-latest-patch-syntax
      with:
        dotnet-version: "6.0.1xx"
        dotnet-quality: "ga"
    - run: dotnet --info
        

