
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['ubuntu-latest']
    name: setup-node@v3 node-version-file check
    steps:

    - run: |
        cd '/home/runner/.dotnet/sdk'
        mkdir 'zzz'
    - name: Checkout
      uses: actions/checkout@main

    - uses: IvanZosimov/setup-dotnet@dotnet-install-dir-fix
      with:
          dotnet-version: '7.0'
      env:
        DOTNET_INSTALL_DIR: "/home/runner/.dotnet/sdk/zzz"

    - run: |
        dotnet --info
        
    
        
  
      

