
name: Context testing
on: 
    workflow_dispatch:
    push:
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    continue-on-error: true
    strategy:
      matrix:
        os: ['macos-latest', 'ubuntu-latest', 'windows-latest']
        version: ["6.0.", "5.0.xx", "5.A", "x5.x", "xx" ]
    name: Dotnet sample
    steps:
          
    - name: Test setup-dotnet v3
      uses: IvanZosimov/setup-dotnet@ADRdotnet
      with: 
        dotnet-version: ${{matrix.version}}

  
      

